apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: 12011/config-server
    ports:
    - name: nodejs-port
      containerPort: 3000
